fix(back): About API tag and excluded webhook endpoints
RezaRahemtola/Area pull request #136
Opened 2023-10-25 21:15 UTC by EdenComp

2023-10-25 21:52 UTC, RezaRahemtola approved these changes

2023-10-26 08:46 UTC, Croos3r requested changes

2023-10-26 08:46 UTC, Croos3r commented on backend/back/src/about/about.controller.ts
> +@ApiTags("About")
Remove that, it's MY linear issue

2023-10-26 10:41 UTC, EdenComp commented on backend/back/src/about/about.controller.ts
> +@ApiTags("About")
osef

2023-10-26 14:30 UTC, Croos3r approved these changes
![LGTM](https://image.lgtmoon.dev/224847)

2023-10-26 14:30 UTC, merged