Added service GItLab to the list of supported services
RezaRahemtola/Area pull request #144
Opened 2023-10-26 15:40 UTC by Croos3r

2023-10-26 15:54 UTC, RezaRahemtola approved these changes

2023-10-26 19:08 UTC, EdenComp requested changes
typo otherwise lgtm

2023-10-26 19:08 UTC, EdenComp commented on backend/back/src/services/seed/1698332919825-CreateGitLabServiceWithScopes.ts
> +	private readonly DISCORD_SERVICE_SCOPES = [
Discord -> Gitlab

2023-10-27 08:28 UTC, Croos3r commented on backend/back/src/services/seed/1698332919825-CreateGitLabServiceWithScopes.ts
> +	private readonly DISCORD_SERVICE_SCOPES = [
you right

2023-10-27 08:58 UTC, EdenComp approved these changes

2023-10-27 08:58 UTC, merged