Backend workflow toggle taking a state
RezaRahemtola/Area pull request #149
Opened 2023-10-28 21:16 UTC by RezaRahemtola

2023-10-28 21:32 UTC, EdenComp approved these changes

2023-10-29 02:12 UTC, Croos3r requested changes

2023-10-29 02:12 UTC, Croos3r commented on backend/back/src/workflows/dto/bulk-workflows.dto.ts
The code is no longer DRY with your changes

Make BulkToggleWorkflowsDto extends IntersectionType(BulkWorkflowsDto, ToggleWorkflowDto)

2023-10-29 02:12 UTC, Croos3r commented on backend/back/src/workflows/workflows.service.ts
> +		return { newState: newState };
```suggestion
		return { newState };
```

2023-10-29 13:25 UTC, Croos3r approved these changes
![LGTM](https://image.lgtmoon.dev/224676)

2023-10-29 13:25 UTC, merged