Tom/are 56 setup theme mobile
RezaRahemtola/Area pull request #179
Opened 2023-11-02 02:34 UTC by Tomi-Tom

2023-11-02 10:38 UTC, RezaRahemtola requested changes

2023-11-02 10:38 UTC, RezaRahemtola commented on frontend/mobile/assets/bolt.png
why ?

2023-11-02 10:38 UTC, RezaRahemtola commented on frontend/mobile/lib/pages/landing.dart
> +  String language = "en";
use the locale variable below instead, all the storage function are already named "locale" and imo it's a better name

2023-11-02 10:38 UTC, RezaRahemtola commented on frontend/mobile/lib/pages/landing.dart
> +        language = storageLanguage;
so update here

2023-11-02 10:38 UTC, RezaRahemtola commented on frontend/mobile/lib/pages/landing.dart
> +      language = newLocale;
same

2023-11-02 10:38 UTC, RezaRahemtola commented on frontend/mobile/lib/pages/landing.dart
> +      locale: Locale(language),
same

2023-11-02 10:38 UTC, RezaRahemtola commented on frontend/mobile/lib/pages/library.dart
> +                }
Are these empty states ? If yes then add them in the translation files instead of hardcoding english (and don't use "1" or "2")

2023-11-02 14:07 UTC, Tomi-Tom commented on frontend/mobile/assets/bolt.png
the old one looked cropped

2023-11-03 08:02 UTC, axel-denis approved these changes

2023-11-03 20:03 UTC, RezaRahemtola approved these changes

2023-11-03 20:04 UTC, merged