Mobile Activity
RezaRahemtola/Area pull request #205
Opened 2023-11-04 23:04 UTC by axel-denis

Fixes ARE-425

2023-11-04 23:06 UTC, Tomi-Tom approved these changes

2023-11-05 00:16 UTC, RezaRahemtola approved these changes

2023-11-05 01:24 UTC, RezaRahemtola requested changes
le rebase a cassé le typage je crois, le fetch ne récupère pas bien la data

2023-11-05 18:26 UTC, RezaRahemtola approved these changes

2023-11-05 18:31 UTC, merged